import "./globals.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import Navbar from './Student/Layout/Navabr'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kingship Technologies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Bruno+Ace&family=Montserrat:wght@100;200;300;400;500;600;700;800&family=Open+Sans:wght@300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      </Head> */}
      <body className={inter.className} style={{ fontFamily: 'Montserrat' }}>
        {/* <Navbar/>  */}
          {children}
   
      </body>
    </html>
  );
}



// import LayoutWithSidebar from "./AnotherLayout";

// export default function AlternativeLayoutPage() {
//   return <>Page with a sidebar</>;
// }

// AlternativeLayoutPage.getLayout = function(page) {
//   return <LayoutWithSidebar>{page}</LayoutWithSidebar>;
// };